#!/bin/bash
echo "Preparing code for Solana Playground..."
echo ""
echo "✅ Program code ready: SOLANA_PLAYGROUND_CODE.rs"
echo "✅ Program ID: wEeoKNhaFsCPYLsscNUy5PpXxNs81vF6CfEArCxLmmr"
echo "✅ Deployer: 61QFkSLNNYnvyBXGT1sekpVMubQogUYEMxhVHoTY63T8"
echo ""
echo "Next steps:"
echo "1. Open https://beta.solpg.io/"
echo "2. Create new Anchor project"
echo "3. Copy code from SOLANA_PLAYGROUND_CODE.rs"
echo "4. Build and Deploy"
echo ""
echo "Keypair for import (first 20 bytes):"
head -c 40 event-tickets/target/deploy/event_tickets-keypair.json | python3 -c "import sys; data=sys.stdin.read(); print('[' + ','.join(str(ord(c)) for c in data[:20]) + '...]')" 2>/dev/null || echo "See event-tickets/target/deploy/event_tickets-keypair.json"
